version: '3.7'

services:
  server:
    container_name: nido_server1
    volumes:
      - ./server:/app

    env_file:
      - .env
    build: ./server
    ports:
      - "8002:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234Qwer
      - POSTGRES_DB=nidodb
    volumes:
      - .postgres_data:/var/lib/postgresql/data/
    ports:
      - "5436:5432"

  nginx:
    build: ./nginx
    volumes:
      - ./server/static:/static
    ports:
      - "81:80"
    depends_on:
      - server

volumes:
  postgres_data:
