FROM python:3.9.4-alpine

RUN pip install --upgrade pip

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . /app

WORKDIR /app
RUN pip install watchdog

COPY ./entrypoint.sh /
ENTRYPOINT ["sh", "/entrypoint.sh"]

