FROM python:3.9.4-alpine



COPY . /app

WORKDIR /app


ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN pip install --upgrade pip
COPY ./requirements.txt .

RUN apk add --virtual .build-deps --no-cache postgresql-dev gcc python3-dev musl-dev && \
        pip install --no-cache-dir -r requirements.txt && \
        apk --purge del .build-deps



RUN apk add --no-cache libpq

RUN pip install watchdog

COPY ./entrypoint.sh /
ENTRYPOINT ["sh", "/entrypoint.sh"]

